name: imod-dsd
channels:
  - conda-forge
dependencies:
  - xarray
  - pandas
  - numpy
  - matplotlib
  - dask
  - geopandas
  - python-graphviz
  - flopy
  - rasterio
  - numba
  - affine
  - pip:
    git+https://gitlab.com/deltares/imod/imod-python.git
